const Job_category_list = [
  {
    code: "PW",
    de: "Personalwesen",
    en: "Human Resources",
    fr: "Ressources Humaines",
  },
  {
    code: "GEMESO",
    de: "Gesundheit, Medizin, Soziales",
    en: "Healthcare, medicine, social services",
    fr: "Santé, Médecine, Social",
  },
  {
    code: "REST",
    de: "Rechts- und Steuerwesen",
    en: "Law and tax advisory",
    fr: "Droit et impôts",
  },
  {
    code: "UNMA",
    de: "Unternehmensführung/Management",
    en: "Company management",
    fr: "Direction générale, Management",
  },
  {
    code: "COBE",
    de: "Consulting, Beratung",
    en: "Consulting",
    fr: "Consulting, Conseil",
  },
  {
    code: "MAVEDE",
    de: "Marketing, PR, Werbung, Design/Multimedia",
    en: "Marketing, PR, advertising, design/multimedia",
    fr: "Marketing, Relations Publiques, Publicité, Design/Multimédia",
  },
  {
    code: "FENAT",
    de: "Forschung/Entwicklung, High-tech/nat.-wiss. Berufe",
    en: "Research and development, High-Tech, scientific professions",
    fr: "R&D / Haute technologie / Sciences naturelles",
  },
  {
    code: "SEMA",
    de: "Sekretariat/Office Management/Verwaltung",
    en: "Secretarial/office management/administrative services",
    fr: "Secrétariat et Support administratif",
  },
  {
    code: "ORPRO",
    de: "Organisation/Projektmanagement",
    en: "Organisation/project management",
    fr: "Organisation / Gestion de projets",
  },
  {
    code: "TRAVELOLA",
    de: "Transport, Verkehr, Logistik, Lager",
    en: "Transport, logistics, warehousing",
    fr: "Transport & Logistique",
  },
  {
    code: "ITTK",
    de: "IT/Telekommunikation",
    en: "IT/Telecommunications",
    fr: "Informatique et télécommunications",
  },
  {
    code: "VEVE",
    de: "Vertrieb, Verkauf",
    en: "Sales",
    fr: "Vente et distribution",
  },
  {
    code: "BAARHAUM",
    de: "Bauwesen, Handwerk, Umwelt",
    en: "Construction, handicraft, environment",
    fr: "Construction , Artisanat, Environnement",
  },
  {
    code: "TEBE",
    de: "Technische Berufe (Ingenieure, Konstrukteure, Architekten)",
    en: "Technical professions (engineers, draftsmen, architects)",
    fr: "Ingénierie, Architecture & Technique",
  },
  {
    code: "EIMA",
    de: "Einkauf, Materialwirtschaft",
    en: "Purchasing, materials management",
    fr: "Achat, Gestion des stocks",
  },
  {
    code: "FIRECO",
    de: "Finanz- u. Rechnungswesen, Controlling, Versicherung",
    en: "Finance and accounting, controlling, insurance",
    fr: "Comptabilité et Finances, Contrôle de gestion, Assurances",
  },
  { code: "ING", de: "Ingenieure", en: "Engineers", fr: "Ingénierie" },
  {
    code: "PFLEGE",
    de: "Pflege-/Arzthelferberufe",
    en: "Nursing profession, medical secretary",
    fr: "Personnel soignant et assistants médicaux",
  },
  {
    code: "CC",
    de: "Call-Center",
    en: "Call centre",
    fr: "Centre d'appel",
  },
  {
    code: "HW",
    de: "Handwerk",
    en: "Craft, manufacturing",
    fr: "Artisanat, production",
  },
  { code: "ARZT", de: "Arztberufe", en: "Physicians", fr: "Médecins" },
  {
    code: "SOZ",
    de: "Sozialberufe",
    en: "Social professions",
    fr: "Services sociaux",
  },
  {
    code: "ARCH",
    de: "Architekten",
    en: "Architects",
    fr: "Architecture",
  },
  {
    code: "HOGATO",
    de: "Hotel-/Gastgewerbe, Tourismus, Empfang",
    en: "Hotels and restaurants, tourism, reception",
    fr: "Hôtellerie - Restauration - Tourisme",
  },
  {
    code: "GES",
    de: "Gesundheitsberufe",
    en: "Healthcare professions",
    fr: "Santé",
  },
  {
    code: "WAT",
    de: "Wissenschaft, Aus-/Weiterbildung",
    en: "Science, vocational /professional training",
    fr: "Science & Recherche Scientifique / Formation professionnelle",
  },
  {
    code: "IT",
    de: "Informationstechnologie",
    en: "Information technology",
    fr: "Technologies de l'information",
  },
  {
    code: "TK",
    de: "Telekommunikation",
    en: "Telecommunications",
    fr: "Télécommunications",
  },
  {
    code: "BUCHRECH",
    de: "Buchhaltung/Rechnungswesen",
    en: "Accountancy",
    fr: "Comptabilité",
  },
  {
    code: "LAGFACH",
    de: "Lagerfachkräfte",
    en: "Warehouse worker",
    fr: "Magasiniers",
  },
  {
    code: "BAU",
    de: "Bauwesen",
    en: "Civil engineering",
    fr: "Bâtiment",
  },
  {
    code: "TESO",
    de: "Sonstige technische Berufe",
    en: "other technical professions",
    fr: "Autres professions techniques",
  },
  {
    code: "BHG",
    de: "Bauhauptgewerbe",
    en: "Main construction industry",
    fr: "Construction",
  },
];

export default Job_category_list;
