const State_List = [
  {
    country: "A",
    original_state: "Burgenland",
    state_de: "Burgenland",
  },
  { country: "A", original_state: "Kärnten", state_de: "Kärnten" },
  {
    country: "A",
    original_state: "Niederösterreich",
    state_de: "Niederösterreich",
  },
  {
    country: "A",
    original_state: "Oberösterreich",
    state_de: "Oberösterreich",
  },
  { country: "A", original_state: "Salzburg", state_de: "Salzburg" },
  {
    country: "A",
    original_state: "Steiermark",
    state_de: "Steiermark",
  },
  { country: "A", original_state: "Tirol", state_de: "Tirol" },
  {
    country: "A",
    original_state: "Vorarlberg",
    state_de: "Vorarlberg",
  },
  {
    country: "A",
    original_state: "Wien",
    state_de: "Wien",
    state_fr: "Vienne",
    state_nl: "Wenen",
    state_it: "Vienna",
  },
  {
    country: "BE",
    original_state: "Bruxelles-Capitale",
    state_fr: "Bruxelles-Capitale",
    state_nl: "Brussels Hoofdstedelijk Gewest",
  },
  {
    country: "BE",
    original_state: "Région Flamande",
    state_fr: "Région Flamande",
    state_nl: "Vlaams Gewest",
  },
  {
    country: "BE",
    original_state: "Région Wallonne",
    state_fr: "Région Wallonne",
    state_nl: "Waals Gewest",
  },
  {
    country: "CH",
    original_state: "Aargau",
    state_de: "Aargau",
    state_fr: "Argovie",
    state_it: "Argovia",
  },
  {
    country: "CH",
    original_state: "Appenzell Ausserrhoden",
    state_de: "Appenzell Ausserrhoden",
    state_fr: "Appenzell Rhodes-Extérieures",
    state_it: "Appenzello Esterno",
  },
  {
    country: "CH",
    original_state: "Appenzell Innerrhoden",
    state_de: "Appenzell Innerrhoden",
    state_fr: "Appenzell Rhodes-Intérieures",
    state_it: "Appenzello Interno",
  },
  {
    country: "CH",
    original_state: "Basel-Landschaft",
    state_de: "Basel-Landschaft",
    state_fr: "Bâle-Campagne",
    state_it: "Basilea Campagna",
  },
  {
    country: "CH",
    original_state: "Basel-Stadt",
    state_de: "Basel-Stadt",
    state_fr: "Bâle-Ville",
    state_it: "Basilea Città",
  },
  {
    country: "CH",
    original_state: "Bern",
    state_de: "Bern",
    state_fr: "Berne",
    state_it: "Berna",
  },
  {
    country: "CH",
    original_state: "Freiburg",
    state_de: "Freiburg",
    state_fr: "Fribourg",
    state_it: "Friburgo",
  },
  {
    country: "CH",
    original_state: "Genf",
    state_de: "Genf",
    state_fr: "Genève",
    state_it: "Ginevra",
  },
  {
    country: "CH",
    original_state: "Glarus",
    state_de: "Glarus",
    state_fr: "Glaris",
    state_it: "Glarona",
  },
  {
    country: "CH",
    original_state: "Graubünden",
    state_de: "Graubünden",
    state_fr: "Grisons",
    state_it: "Grigioni",
  },
  {
    country: "CH",
    original_state: "Jura",
    state_de: "Jura",
    state_fr: "Jura",
    state_it: "Giura",
  },
  {
    country: "CH",
    original_state: "Luzern",
    state_de: "Luzern",
    state_fr: "Lucerne",
    state_it: "Lucerna",
  },
  {
    country: "CH",
    original_state: "Neuenburg",
    state_de: "Neuenburg",
    state_fr: "Neuchâtel",
    state_it: "Neuchâtel",
  },
  {
    country: "CH",
    original_state: "Nidwalden",
    state_de: "Nidwalden",
    state_fr: "Nidwald",
    state_it: "Nidvaldo",
  },
  {
    country: "CH",
    original_state: "Obwalden",
    state_de: "Obwalden",
    state_fr: "Obwald",
    state_it: "Obvaldo",
  },
  {
    country: "CH",
    original_state: "Sankt Gallen",
    state_de: "Sankt Gallen",
    state_fr: "Saint-Gall",
    state_it: "San Gallo",
  },
  {
    country: "CH",
    original_state: "Schaffhausen",
    state_de: "Schaffhausen",
    state_fr: "Schaffhouse",
    state_it: "Sciaffusa",
  },
  {
    country: "CH",
    original_state: "Schwyz",
    state_de: "Schwyz",
    state_fr: "Schwytz",
    state_it: "Svitto",
  },
  {
    country: "CH",
    original_state: "Solothurn",
    state_de: "Solothurn",
    state_fr: "Soleure",
    state_it: "Soletta",
  },
  {
    country: "CH",
    original_state: "Thurgau",
    state_de: "Thurgau",
    state_fr: "Thurgovie",
    state_it: "Turgovia",
  },
  {
    country: "CH",
    original_state: "Ticino",
    state_de: "Ticino",
    state_fr: "Tessin",
    state_it: "Ticino",
  },
  {
    country: "CH",
    original_state: "Uri",
    state_de: "Uri",
    state_fr: "Uri",
    state_it: "Uri",
  },
  {
    country: "CH",
    original_state: "Waadt",
    state_de: "Waadt",
    state_fr: "Vaud",
    state_it: "Vaud",
  },
  {
    country: "CH",
    original_state: "Wallis",
    state_de: "Wallis",
    state_fr: "Valais",
    state_it: "Vallese",
  },
  {
    country: "CH",
    original_state: "Zug",
    state_de: "Zug",
    state_fr: "Zug",
    state_it: "Zugo",
  },
  {
    country: "CH",
    original_state: "Zürich",
    state_de: "Zürich",
    state_fr: "Zurich",
    state_it: "Zurigo",
  },
  {
    country: "D",
    original_state: "Baden-Württemberg",
    state_de: "Baden-Württemberg",
  },
  { country: "D", original_state: "Bayern", state_de: "Bayern" },
  { country: "D", original_state: "Berlin", state_de: "Berlin" },
  {
    country: "D",
    original_state: "Brandenburg",
    state_de: "Brandenburg",
  },
  { country: "D", original_state: "Bremen", state_de: "Bremen" },
  { country: "D", original_state: "Hamburg", state_de: "Hamburg" },
  { country: "D", original_state: "Hessen", state_de: "Hessen" },
  {
    country: "D",
    original_state: "Mecklenburg-Vorpommern",
    state_de: "Mecklenburg-Vorpommern",
  },
  {
    country: "D",
    original_state: "Niedersachsen",
    state_de: "Niedersachsen",
  },
  {
    country: "D",
    original_state: "Nordrhein-Westfalen",
    state_de: "Nordrhein-Westfalen",
  },
  {
    country: "D",
    original_state: "Rheinland-Pfalz",
    state_de: "Rheinland-Pfalz",
  },
  { country: "D", original_state: "Saarland", state_de: "Saarland" },
  { country: "D", original_state: "Sachsen", state_de: "Sachsen" },
  {
    country: "D",
    original_state: "Sachsen-Anhalt",
    state_de: "Sachsen-Anhalt",
  },
  {
    country: "D",
    original_state: "Schleswig-Holstein",
    state_de: "Schleswig-Holstein",
  },
  { country: "D", original_state: "Thüringen", state_de: "Thüringen" },
  {
    country: "F",
    original_state: "Auvergne-Rhône-Alpes",
    state_fr: "Auvergne-Rhône-Alpes",
  },
  {
    country: "F",
    original_state: "Bourgogne-Franche-Comté",
    state_fr: "Bourgogne-Franche-Comté",
  },
  { country: "F", original_state: "Bretagne", state_fr: "Bretagne" },
  {
    country: "F",
    original_state: "Centre-Val de Loire",
    state_fr: "Centre-Val de Loire",
  },
  { country: "F", original_state: "Corse", state_fr: "Corse" },
  { country: "F", original_state: "DOM-TOM", state_fr: "DOM-TOM" },
  { country: "F", original_state: "Grand Est", state_fr: "Grand Est" },
  {
    country: "F",
    original_state: "Hauts-de-France",
    state_fr: "Hauts-de-France",
  },
  {
    country: "F",
    original_state: "Ile-de-France",
    state_fr: "Ile-de-France",
  },
  { country: "F", original_state: "Normandie", state_fr: "Normandie" },
  {
    country: "F",
    original_state: "Nouvelle-Aquitaine",
    state_fr: "Nouvelle-Aquitaine",
  },
  { country: "F", original_state: "Occitanie", state_fr: "Occitanie" },
  {
    country: "F",
    original_state: "Pays de la Loire",
    state_fr: "Pays de la Loire",
  },
  {
    country: "F",
    original_state: "Provence-Alpes-Côte d'Azur",
    state_fr: "Provence-Alpes-Côte d'Azur",
  },
  { country: "NL", original_state: "Drenthe", state_nl: "Drenthe" },
  { country: "NL", original_state: "Flevoland", state_nl: "Flevoland" },
  { country: "NL", original_state: "Friesland", state_nl: "Friesland" },
  {
    country: "NL",
    original_state: "Gelderland",
    state_nl: "Gelderland",
  },
  { country: "NL", original_state: "Groningen", state_nl: "Groningen" },
  { country: "NL", original_state: "Limburg", state_nl: "Limburg" },
  {
    country: "NL",
    original_state: "Noord-Brabant",
    state_nl: "Noord-Brabant",
  },
  {
    country: "NL",
    original_state: "Noord-Holland",
    state_nl: "Noord-Holland",
  },
  {
    country: "NL",
    original_state: "Overijssel",
    state_nl: "Overijssel",
  },
  {
    country: "NL",
    original_state: "Utrecht",
    state_nl: "Utrecht",
  },
  { country: "NL", original_state: "Zeeland", state_nl: "Zeeland" },
  {
    country: "NL",
    original_state: "Zuid-Holland",
    state_nl: "Zuid-Holland",
  },
  { country: "NO", original_state: "Midt-Norge" },
  { country: "NO", original_state: "Nord-Norge" },
  { country: "NO", original_state: "Østlandet" },
  { country: "NO", original_state: "Overseas territories" },
  { country: "NO", original_state: "Sørlandet" },
  { country: "NO", original_state: "Vestlandet" },
  { country: "SE", original_state: "Blekinge" },
  { country: "SE", original_state: "Dalarna" },
  { country: "SE", original_state: "Gävleborg" },
  { country: "SE", original_state: "Gotland" },
  { country: "SE", original_state: "Halland" },
  { country: "SE", original_state: "Jämtland" },
  { country: "SE", original_state: "Jönköping" },
  { country: "SE", original_state: "Kalmar" },
  { country: "SE", original_state: "Kronoberg" },
  { country: "SE", original_state: "Norrbotten" },
  { country: "SE", original_state: "Örebro" },
  { country: "SE", original_state: "Östergötland" },
  { country: "SE", original_state: "Skåne" },
  { country: "SE", original_state: "Södermanland" },
  { country: "SE", original_state: "Södermanland" },
  { country: "SE", original_state: "Stockholm" },
  { country: "SE", original_state: "Uppsala" },
  { country: "SE", original_state: "Värmland" },
  { country: "SE", original_state: "Västerbotten" },
  { country: "SE", original_state: "Västernorrland" },
  { country: "SE", original_state: "Västmanland" },
  { country: "SE", original_state: "Västra Götaland" },
];

export default State_List;
